### ISSUE TITLE
Underline and Italic Styles Not Working on Heading Component

### ISSUE THREAD

**Issue by biswajitsundara** [biswajitsundara/ghewar#1]
The underline and italic styles are not being applied correctly to the text in the Heading component. While other text styles like bold appear to work as expected, both underline and italic do not affect the text.

**Steps to Reproduce:**

- Use the Heading component and set the textStyle prop to "underline" or "italic".
- Render the component.
- Observe that the text is neither underlined nor italicized.

```jsx
<Heading level={3} textStyle="italic">
  This text is italicized.
</Heading>

<Heading level={3} textStyle="underline">
  This text is italicized.
</Heading>
```

**Expected Behavior:**

The `textStyle` prop italic, underline should turn the text italic/underline respectively.

**Actual Behavior:**

The `textStyle` prop italic, underline doesn't turn the text italic/underline respectively.

**Comment by Halsjsko** [comment]
如果直接使用textStyle属性不起作用，可以考虑使用 CSS 类来实现斜体和下划线样式。
对于斜体，可以创建一个 CSS 类，例如：
.italic-text {
   font-style: italic;
 }
对于下划线，可以创建另一个 CSS 类，例如：
.underlined-text {
   text-decoration: underline;
 }
在你的组件中，使用className属性来应用这些 CSS 类，而不是使用textStyle属性：
对于斜体：
<Heading level={3} className="italic-text">
  This text is italicized.
</Heading>
对于下划线：
<Heading level={3} className="underlined-text">
  This text is underlined.
</Heading>

**Comment by biswajitsundara** [comment]
That's right @Halsjsko 
The issue is fixed and will be available in next release
